http:
  port: "8081"
db:
  host: "db4free.net"
  port: "3306"
  user: "ayanc1"
  password: "![Z5B4Rdpe6BRVdt40SGJ29Q==]"
  database: "movies_bms"
email:
  host: "smtp.gmail.com"
  port: "587"
  user: "anurag.a.puri@apisero.com"
